name: pqc-workshop
channels:
  - conda-forge
dependencies:
  - python=3.13
  - setuptools
  - pip
  - pip:
      - dilithium_py
  - typing
  - numpy
  - pandas
  - jupyter
  - jupyterlab
  - ipykernel
  - wheel
